server:
  port: 8001

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379

short-link:
  domain:
    default: localhost:8001
  stats:
    locale:
      amap-key: 50622c42f5c538e64e5582335f53b13e
  goto-domain:
    white-list:
      enable: true
      details:
        - leetcode.cn
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - google.com
        - bing.com
        - baidu.com
        - facebook.com
        - linkedin.com
        - instagram.com
        - weixin.qq.com
        - weibo.com
        - amazon.com
        - taobao.com
        - jd.com
        - alibaba.com
        - youtube.com
        - bilibili.com
        - bbc.com/news
        - cnn.com
        - xinhuanet.com
        - coursera.org
        - edx.org
        - github.com
        - stackoverflow.com
        - mail.google.com
        - outlook.live.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
rocketmq:
  name-server: common-rocketmq-dev.magestack.cn:9876
  producer:
    group: short-link_project-service_stats-save_pg_cxlong
    topic: short-link_project-service_topic_cxlong
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
  consumer:
    group: short-link_project-service_stats-save_cg_cxlong